name: 'Heck Yes!'
root: '/'
logo: 'https://s3.amazonaws.com/f.cl.ly/items/1b1K0B0118112Q233P0E/logo-b.png'
markdown: redcarpet
highlighter: pygments
permalink: /:title
redcarpet:
    extensions: [with_toc_data]